require 'core'
require 'window'
require 'lsp'
require 'autocompletion'
require 'highlight'
require 'ui'
require 'statusline'
require 'edit'

require 'lang.glsl'
require 'lang.latex'
require 'lang.csv'
